name: MingleIOS
options:
  minimumXcodeGenVersion: 2.38.0
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 6.0
    SWIFT_STRICT_CONCURRENCY: minimal
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0.0
configs:
  Debug: debug
  Release: release
targets:
  MingleIOS:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: MingleIOS
    configFiles:
      Debug: Config/Debug.xcconfig
      Release: Config/Release.xcconfig
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nam.mingleios
        INFOPLIST_FILE: MingleIOS/Info.plist
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
        TARGETED_DEVICE_FAMILY: "1,2"
    scheme:
      testTargets:
        - MingleIOSTests

  MingleIOSTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: MingleIOSTests
    dependencies:
      - target: MingleIOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nam.mingleios.tests
        GENERATE_INFOPLIST_FILE: YES
